# changeNameOfObject intent
---
type: intent
name: changeNameOfObject
slots:
  - name: old
    entity: object
  - name: new
    entity: object
utterances:
  - Maintenant on utilise [new](plop) au lieu de [old](cube)
  - Ce n'est plus un [old](triangle) mais un [new](chat)
  - On renomme [old](cercle) en [new](chien)
  - on appelle [old](cube) [new](plop).
  - on appelle un [old](cube) un [new](plop).
  - on appelle maintenant un [old](cube) un [new](plop).
  - on appelle un [old](cube) un [new](plop) maintenant.
  - On va renommer [old](choucroute) en [new](phénix)
  - On remplace [old](choucroute) par [new](phénix)
  - Remplace [old](bleu) par [new](cheval).
  

# changeGenderOfObject intent
---
type: intent
name: changeGenderOfObject
slots:
  - name: object_name
    entity: object
  - name: object_gender
    entity: gender
utterances:
  - "[object_name](plop) est un mot [object_gender](féminin)"
  - Le mot [object_name](chat) est [object_gender](masculin)
  - Le mot [object_name](chien) est un mot [object_gender](masculin)
  - "[object_name](choucroute) est [object_gender](féminin)"

# object entity
---
type: entity
name: object
automatically_extensible: yes
values:
- cube
- [cercle,rond]
- triangle
- bleu
- vert 
- cheval
- chien
- chat 
- plip
- plop
- phénix
- félix
- choucroute

---
type: entity
name: gender
automatically_extensible: no
values:
- féminin
- masculin

